<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="1" name="Opera(failed)(failed)(failed)" time="3.989" errors="0" timestamp="03 Feb 2022 08:25:09 GMT">
  <testcase classname="TestClass.ValidateLogin" name="Login" time="0.239">
    <failure type="java.lang.AssertionError" message="expected [http://localhost/user/submit_tt.do] but found [http://localhost/login.do]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost/user/submit_tt.do] but found [http://localhost/login.do]
at TestClass.ValidateLogin.Login(ValidateLogin.java:76)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
</testsuite> <!-- Opera(failed)(failed)(failed) -->
